<a href="https://colab.research.google.com/github/nehasupe/AppliedMachinelearning/blob/master/Assignment2_F19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CSCI-P556: Applied Machine Learning
Fall 2018
Assignment #2
---



## Problem 1 (50 points)

In this problem you will be working with Bank Marketing Dataset. We encourage your to look at the description and make yourself comfortable with it: https://archive.ics.uci.edu/ml/datasets/bank+marketing

Two pairs of training and validation sets have been drawn from this dataset for you to work with, namely: 
 -  `train_1.csv` and `valid_1.csv`
 -  `train_2.csv`and `valid_2.csv`
 
Finally, we have also provided a `test.csv` which is common for both settings.

### Task 0: (3 points)

What is the difference between the two sets of train/validation sets? Write your answer here:

### Ans: <!-- Your answers goes here -->


### Task 1 (Data Preprocessing) (12 points)

Before you can train a machine learning model using this dataset, you will have to run a number of preprocessing steps to transform the data into a form which will be acceptable to the model. In this task, you are supposed to carry out the follow steps:

1.  Find all features that have continuous numeric values and normalize them in the same way as you did in Assignment 1. List those features here.
2. Find all categorical features and process them as was discussed in class. List those features and explain what you did.
3. Are there any features which have missing values? (Hint: Missing values aren't always nicely represented and can be misleading sometimes). Find those features and explain how you will handle them.



Write your text-based answers here.


1.   Answer for bullet one
2.   Answer for bullet two
3.   Answer for bullet three



In [0]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # PROBLEM 1, TASK 1 CODE GOES HERE

\### Task 2 (Model $\mathcal{A}$) (10 points)

Train a logistic regression model with $L_2$ regularization on `train_1.csv` after applying the necessary preprocessing steps of Task 1. Use the validation set `valid_1.csv` to choose the best regularization coefficient $\lambda$. Plot a curve with regularization coefficient in the X axis and the validation accuracy on the Y axis.

In [0]:
# PROBLEM 1, TASK 2 CODE GOES HERE

### Task 3 (Model $\mathcal{B}$) (5 points)
Train a logistic regression model with $L_2$ regularization on `train_2.csv` after applying the necessary preprocessing steps of Task 1. Use the validation set `valid_2.csv` to choose the best regularization coefficient $\lambda$. Plot a curve with regularization coefficient in the X axis and the validation accuracy on the Y axis.

In [0]:
# PROBLEM 1, TASK 3 CODE GOES HERE

### Task 4 (Model $\mathcal{C}$) (10 points)

As you have seen in class, due to the specific (and smart) choice of the loss function, a logistic regression classifier happens to predict the posterioir probability $p(y|\mathbf{x})$ for any given sample. It then classifies the samples with $p(y|\mathbf{x}) > 0.5$ as belonging to class $1$ and the rest as belonging to class $0$. Instead, for a fixed threshold of $0.5$, let us consider a dynamic threshold of $\theta$ which can be chosen after a model has been trained.

$$
\ y=
\begin{cases}
1 \text{ if } p(y|\mathbf{x}) \geq \theta \\
\\
0 \text{ if } p(y|\mathbf{x}) < \theta \\
\end{cases}
$$

for $0 \leq \theta \leq 1$.

Train a logistic regression model with $L_2$ regularization on `train_2.csv` after applying the necessary preprocessing steps of Task 1. Use the validation set `valid_2.csv` to choose the best combination of regularization coefficient $\lambda$ and the threshold $\theta$. The best coefficients has to be selected by you after trying out at least five, non-consecutive values. Visualize all these runs.

**Hint**: Look at the documentation of Logistic Regression in sci-kit learn to come up with a plan to implement this.

In [0]:
# PROBLEM 1, TASK 4 CODE GOES HERE

### Task 5 (Report and Conclusion) (10 points)

1.  Give a detailed report on the performance (that is, accuracy) of Models $\mathcal{A}$, $\mathcal{B}$ and $\mathcal{C}$ on the respective training sets, the validation sets and finally the test. Explain any intuition you might have on what might be happening in each of the cases. Please avoid writing unnecessary details which are not pertinent.
2.  Do you think accuracy, the metric which you have used to find the best hyperparameter in all the above tasks, a good metric in this scenario? Explain your choice.



## Problem 2 (50 points)

Consider a regression problem in which the input variable $x$ has only one feature and the target variable $y$ is generated from the input variable $x$ by a polynomial $f(x)$. The function $f$ is such that $$f(x) = \sum_{i=0}^d w_ix^i$$ Please note that a given polynomial function can be completely described by the vector of coefficients $\mathbf{w}$.

### Task 1 (5 points)

Write a function in python which can take the degree of polynomial function as input. The code to generate vector coefficeints $\mathbf{w}$ using this input is already provided. Plot the resulting function for $x \in (-low, high)$. The function should be plot 

In [0]:
import numpy as np
from scipy.special import legendre
import random
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

def get_coefficients(degree):
    """
    The coefficients returned are in the order w_0, w_1, ... , w_{degree}
    """
    return legendre(degree).coefficients[::-1]

def visualize_function(degree, low, high):
	y = 0
	x = np.random.uniform(low, high, 1)
	w = get_coefficients(degree)
  for i in range(degree+1):
    y = y + w[i] * pow(x, i)
	#print(x, y)
	#plt.plot(x, y,'ro')
	#plt.xlabel('x - axis')
	#plt.ylabel('f(x) - axis')
	#plt.title('Visualize function')
	#plt.show()
	return (x, y)
## TEST CASES (The following lines should plot a function)
# visualize_funtion(3, -1, 1)
# visualize_funtion(4, -1, 1)
# visualize_funtion(6, -1, 1)

IndentationError: ignored

### Task 2 (5 points)

Write a function in python that randomly generates a dataset (training data + test data). The function should take the degree of target polynomial as input along with the number of points that should be generated for both the training and the test sets. The polynomial will be represented by the vector of coefficients. The code to calculate these coefficients has been provided. The function should also add random normal noise to the target -- i.e. the noise should be drawn from a normal distribution with mean $\mu=0$ and standard deviation = $\sigma^2$. Thus: 
$$y=\sum_{i=0}^d w_ix^i + \mathcal{N}(0, \sigma^2)$$



In [0]:
def generate_dataset(degree, n_train, n_test, sigma):
    """
    - n_train - Number of training samples
    - n_test - Number of test samples
    - X_train is an array of size (n_train $\times$ 1)
    - y_train is an array of size (n_train $\times$ 1)
    - X_test is an array of size (n_test $\times$ 1)
    - y_test is an array of size (n_test $\times$ 1)
    """
    w = get_coefficients(degree)
    X_train = [0]*n_train
    y_train = [0]*n_train
    X_test = [0]*n_test
    y_test = [0]*n_test
    for i in range(n_train):
    	(x, y) = visualize_function(degree, -1, 1)
    	y = y + np.random.normal(0, pow(sigma, 2),size=None)
    	X_train[i] = x
    	y_train[i] = y
    for i in range(n_test):
    	(x, y) = visualize_function(degree, -1, 1)
    	#y = y + np.random.normal(0, pow(sigma, 2),size=None)
    	X_test[i] = x
    	y_test[i] = y
    #plt.plot(X_train, y_train,'ro')
    #plt.show()
    #plt.plot(X_test, y_test,'ro')
    #plt.show()
    return X_train, y_train, X_test, y_test

### Task 3 (20 points)

1.   Use the function written in Task 2 to generate a dataset of degree $10$, with $20$ samples each in the training and test sets. The standard deviation of the noise should be $0.2$.
2.   Plot the generated points of the train set over the function. Make use the function you wrote in Task 1 to do so. The resultant plot should not only contain the function in blue color but also the generated points in the train set in red color.
3.   Fit two linear regressions models: $\mathcal{A}$ and $\mathcal{B}$ on the given training data. Model $\mathcal{A}$ should be quadratic and Model $\mathcal{B}$ should be of degree $10$. How would you create such models?
4. Calculate the training error and testing error on both these models and report them nicely in a table.
5. Explain the results:
 - Are the results as expected or surprising? Explain your stance.
 - Give a detailed explanation of why this happens.
 
 **Hint**: You are free (in fact encouraged) to design new experiments under the same paradigm to understand what is happening. You can buttress your explanation with any plots which you might generate from such new experiments.

 
Note: _There is no preference over the size of the answer but please note that you shouldn't write anything that is not pertinent. While being terse, your answer should clearly convey the intuition. Also, use logical number code/text cells---i.e. every subquestion in a given task which can be considered a logical unit should be present in one cell. Do not make one cell unnecessarily long by putting multiple answers in it or split a given answer over multiple cells. Use your best judgement.

In [0]:
(X_train, y_train, X_test, y_test) = generate_dataset(10, 20, 20, 0.2)
poly = PolynomialFeatures(degree=2)
X_train = poly.fit_transform(X_train)
model = LinearRegression()
model.fit(X_train, y_train)
y_poly_pred = model.predict(X_train)
print(model.coef)





[[ 1.00000000e+00 -6.19367793e-01  3.83616463e-01]
 [ 1.00000000e+00  3.82131007e-01  1.46024107e-01]
 [ 1.00000000e+00  7.33714682e-01  5.38337234e-01]
 [ 1.00000000e+00  1.44513376e-01  2.08841160e-02]
 [ 1.00000000e+00 -2.30993568e-01  5.33580285e-02]
 [ 1.00000000e+00 -5.87092616e-01  3.44677739e-01]
 [ 1.00000000e+00  3.69618120e-01  1.36617554e-01]
 [ 1.00000000e+00  8.17967068e-01  6.69070125e-01]
 [ 1.00000000e+00  6.11196831e-03  3.73561566e-05]
 [ 1.00000000e+00 -4.07821870e-01  1.66318678e-01]
 [ 1.00000000e+00  1.57418899e-01  2.47807098e-02]
 [ 1.00000000e+00 -9.07648417e-01  8.23825649e-01]
 [ 1.00000000e+00  1.90357563e-01  3.62360017e-02]
 [ 1.00000000e+00  3.21801029e-01  1.03555902e-01]
 [ 1.00000000e+00 -9.21258974e-01  8.48718097e-01]
 [ 1.00000000e+00 -4.43042588e-01  1.96286735e-01]
 [ 1.00000000e+00  4.69504042e-01  2.20434045e-01]
 [ 1.00000000e+00 -9.03427249e-01  8.16180795e-01]
 [ 1.00000000e+00  9.35065153e-01  8.74346840e-01]
 [ 1.00000000e+00  1.04888337e-

### Task 4 (20 points)

1.  Use the function written in Task 2 to generate a dataset of degree 45, with 20 samples each in the training and test sets. There should be no noise in the samples.
2.  Repeat steps 2 to 4 from Task 3 for this dataset.
3.  This target doesn't have noise like the previous one. Does this make the result surprising? Explain your stance. Also give a detailed explanation of why this happens.

**Hint**: You are free (in fact encouraged) to design new experiements under the same paradigm to understand what is happening. You can buttress your explanation with any plots which you might generate from such new experiments.